name: Update in html file

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/10 * * * *'

jobs:
  build:
    runs-on:  windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.3.4


      - uses: nanasess/setup-chromedriver@v1
      - run: chromedriver --url-base=/wd/hub &

      - name: Setup Python Environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install Requirements
        run: pip install -r requirements.txt

      - name: result script
        run: |
          export id=${{ secrets.ID }}
          export pass=${{ secrets.PASS }}
          python3 resultStatus.py